fixed regex of apache license sentence

diff --git a/.github/workflows/check-apache-license.yaml b/.github/workflows/check-apache-license.yaml
--- a/.github/workflows/check-apache-license.yaml
+++ b/.github/workflows/check-apache-license.yaml
@@ -18,7 +18,7 @@ jobs:
           .github/scripts/pr-issue-info/apache-check.md
     - name: Check for Apache License
       run: |
-        echo "$BODY" | grep -iPq "I submit this contribution under the Apache-2.0 license." || echo "CHECK_FAILED=true" >> $GITHUB_ENV
+        echo "$BODY" | grep -iPq "^I submit this contribution under the Apache-2.0 license.$" || echo "CHECK_FAILED=true" >> $GITHUB_ENV
     - name: Delete comment if license is fixed
       if: env.CHECK_FAILED != 'true'
       uses: thollander/actions-comment-pull-request@v2
