testing username

diff --git a/.github/workflows/validate-pr-title.yaml b/.github/workflows/validate-pr-title.yaml
--- a/.github/workflows/validate-pr-title.yaml
+++ b/.github/workflows/validate-pr-title.yaml
@@ -1,27 +1,26 @@
 name: validate-pr-title
 on:
-  pull_request_target:
+  pull_request:
     types: [opened, synchronize, edited, reopened]
     branches: 
       - master
 
-env:
-  USERNAME: ${{ github.event.pull_request.user.login }}
-  TITLE: ${{ github.event.pull_request.title }}
-  ERROR_MSG: "The PR title does not match the required format: <fix|build|update|feat|ci>(<tag>): <title>"
-
 jobs:
   title-check:
     runs-on: ubuntu-latest
+    env:
+      ERROR_MSG: "The PR title does not match the required format: <fix|build|update|feat|ci>(<tag>): <title>"
     steps:
     - name: Print PR Title
-      run: echo "$TITLE"
+      run: echo "${{ github.event.pull_request.title }}"
     - name: Check PR Title
       run: |
-        echo "$TITLE" | grep -Pq '^(fix|build|update|feat|ci)\([a-z]+\): [a-z]' || (echo "$ERROR_MSG" && exit 1)
+        echo "${{ github.event.pull_request.title }}" | grep -Pq '^(fix|build|update|feat|ci)\([a-z]+\): [a-z]' || (echo "$ERROR_MSG" && exit 1)
   labels-check:
     runs-on: ubuntu-latest
     steps:
+    - name: Get username
+      run: echo "USERNAME=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
     - name: Check user username
       run: |
         username_list=("freitasmillena" "cxMiguelSilva" "cx-henriqueAlvelos" "pereiramarco011" "kaplanlior" "dependabot" "gabriel-cx" "joaoReigota1" "asofsilva")
@@ -40,7 +39,8 @@ jobs:
         fi
     - name: Add feature or feature request label
       run: |
-        if [[ "$TITLE" == feat* ]]; then
+        title="${{ github.event.pull_request.title }}"
+        if [[ "$title" == feat* ]]; then
           if [[ "$IS_MEMBER" == "true" ]]; then
             echo "Adding 'feature' label..."
             curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels -d '{"labels": ["feature"]}'
@@ -51,7 +51,8 @@ jobs:
         fi
     - name: Add bug label
       run: |
-        if [[ "$TITLE" == bug* ]]; then
+        title="${{ github.event.pull_request.title }}"
+        if [[ "$title" == bug* ]]; then
           echo "Adding 'bug' label..."
           curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels -d '{"labels": ["bug"]}'
         fi
@@ -63,9 +64,10 @@ jobs:
         fi
     - name: Check title for keywords of platforms and cloud providers to add labels
       run: |
+        title="${{ github.event.pull_request.title }}"
         declare -A keywords=(["docker"]="docker" ["dkr"]="docker" ["dockerfile"]="dockerfile" ["ansible"]="ansible" ["aws"]="aws" ["gRPC"]="gRPC" ["gcp"]="gcp" ["cloudformation"]="cloudformation" ["cfn"]="cloudformation" ["azure"]="azure" ["arm"]="arm" ["alicloud"]="alicloud" ["tf"]="terraform" ["terraform"]="terraform" ["openapi"]="openapi" ["kubernetes"]="kubernetes" ["k8s"]="kubernetes")
         for keyword in "${!keywords[@]}"; do
-          if echo "$TITLE" | grep -iq "$keyword"; then
+          if echo "$title" | grep -iq "$keyword"; then
             label=${keywords[$keyword]}
             echo "Adding '$label' label..."
             curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels -d "{\"labels\": [\"$label\"]}"
